// Package fold implements Unicode Simple Case Folding for the LCS registry.
//
// Key names, value names and hive names are case-insensitive but
// case-preserving. loregd stores each name as written and, beside it, a
// folded form, and every lookup compares the folded forms as bytes. That
// only works if loregd and the kernel fold identically: the kernel
// compares names by the same rule, and a name the two fold differently is
// a key that exists for one and not for the other.
//
// The fold is therefore not derived from the Go standard library, whose
// case tables are lowercasing rather than folding and lag the pinned
// Unicode version, but from casefold_table.go — generated by the kernel's
// own generator, pkm/tools/lcs/generate_casefold_table.py, from the same
// CaseFolding.txt (status C and S rows, Unicode 16.0.0) that produces the
// kernel's table. The two tables are the same parse of the same file.
//
// To regenerate after a Unicode version bump:
//
//	python3 pkm/tools/lcs/generate_casefold_table.py \
//	    --input CaseFolding.txt \
//	    --out pkm/crates/lcs-core/src/casefold_table.rs \
//	    --go-out loregd/internal/fold/casefold_table.go
//
// Both outputs must land together; regenerating one side alone recreates
// the split this package exists to prevent.
package fold

// Rune returns the Unicode Simple Case Folding of r: the status C or S
// mapping from CaseFolding.txt when there is one, otherwise r itself.
// The lookup mirrors the kernel's — a binary search over the range table,
// then over the pair table — so the two agree by construction.
func Rune(r rune) rune {
	lo, hi := 0, len(caseFoldRanges)
	for lo < hi {
		mid := lo + (hi-lo)/2
		rg := caseFoldRanges[mid]
		switch {
		case r < rg.start:
			hi = mid
		case r > rg.end:
			lo = mid + 1
		default:
			return rg.mappedStart + (r - rg.start)
		}
	}
	lo, hi = 0, len(caseFoldPairs)
	for lo < hi {
		mid := lo + (hi-lo)/2
		p := caseFoldPairs[mid]
		switch {
		case r < p.source:
			hi = mid
		case r > p.source:
			lo = mid + 1
		default:
			return p.target
		}
	}
	return r
}

// String returns the Unicode Simple Case Folded form of s, folding each
// rune through Rune. It is applied at write time to produce the
// name_folded and child_name_folded columns; queries then compare the
// folded forms as plain bytes.
func String(s string) string {
	// Fast path: a string that is already folded is returned as is,
	// without allocating.
	allFolded := true
	for _, r := range s {
		if Rune(r) != r {
			allFolded = false
			break
		}
	}
	if allFolded {
		return s
	}

	buf := make([]rune, 0, len(s))
	for _, r := range s {
		buf = append(buf, Rune(r))
	}
	return string(buf)
}
