[package]
name        = "dev.peios.loregd-debugsource"
description = "Debug sources for the Peios local registry daemon"

[dependencies]
"dev.peios.loregd-debuginfo" = "= {{version}}-1"

[files]
"@source:LICENSE"   = "usr/share/licenses/dev.peios.loregd-debugsource/LICENSE"
":licenses/**"      = "usr/share/licenses/dev.peios.loregd-debugsource/third-party"
":usr/src/debug/**" = "usr/src/debug"
